# Generated by Django 4.0.3 on 2022-05-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_corpuser_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpuser',
            name='contact',
            field=models.CharField(default='', max_length=100),
        ),
    ]
