# Generated by Django 4.0.4 on 2022-05-23 08:58

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_corpuser_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpuser',
            name='verification_doc',
            field=models.FileField(default='', storage=gdstorage.storage.GoogleDriveStorage(), upload_to='corp'),
        ),
    ]
