# Generated by Django 4.0.4 on 2022-05-27 04:58

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_corpuser_verification_doc'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('website', models.URLField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('contact', models.CharField(default='', max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=100)),
                ('verification_doc', models.FileField(default='', storage=gdstorage.storage.GoogleDriveStorage(), upload_to='coll')),
            ],
        ),
    ]
