# Generated by Django 4.0.4 on 2022-05-28 10:06

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_coluser'),
    ]

    operations = [
        migrations.AddField(
            model_name='coluser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 5, 28, 10, 5, 16, 646862, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coluser',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='corpuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='corpuser',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
