# Generated by Django 4.0.4 on 2022-06-02 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_coluser_verification_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coluser',
            old_name='city',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='corpuser',
            old_name='city',
            new_name='district',
        ),
    ]
